/* Hardwood public shell and core-page renderers. Same-origin JSON only. */
(function(){
  "use strict";
  var NAV=[
    ["home","Home","index.html"],["games","Games","games.html"],["players","Players","players.html"],
    ["teams","Teams","teams.html"],["standings","Standings","standings.html"],["research","Research","deepdive.html"],["accuracy","Accuracy","accuracy.html"]
  ];
  var MORE=[
    ["Availability","availability.html","Injuries and expected status"],["Compare players","compare.html","Side-by-side player view"],
    ["Player impact","player_impact.html","Impact components"],["Situation explorer","situation.html","Score and time states"],
    ["Data explorer","explorer.html","Published datasets"],["Game reports","report_archive.html","Pre-tip report archive"],
    ["Methodology","primer.html","How to read the numbers"],["Operations","board.html","Build and queue status"]
  ];
  var GROUPS={"":"home","index.html":"home","games.html":"games","game_report_v2.html":"games","report_archive.html":"games","availability.html":"games","players.html":"players","player.html":"players","compare.html":"players","player_impact.html":"players","teams.html":"teams","team.html":"teams","coach.html":"teams","gm.html":"teams","standings.html":"standings","deepdive.html":"research","situation.html":"research","primer.html":"research","accuracy.html":"accuracy"};
  var state={};
  function $(id){return document.getElementById(id)}
  function qa(sel,root){return Array.prototype.slice.call((root||document).querySelectorAll(sel))}
  function has(v){return v!==null&&v!==undefined&&v!==""}
  function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]})}
  function first(o,keys){for(var i=0;i<keys.length;i++){var v=o&&o[keys[i]];if(has(v))return v}return null}
  function num(v){if(v===true||v===false||!has(v))return null;var n=Number(v);return Number.isFinite(n)?n:null}
  function fixed(v,d){var n=num(v);return n===null?"—":n.toFixed(d==null?1:d)}
  function signed(v,d){var n=num(v);return n===null?"—":(n>0?"+":"")+n.toFixed(d==null?1:d)}
  function prob(v){var n=num(v);if(n===null)return null;if(n>1&&n<=100)n/=100;return n>=0&&n<=1?n:null}
  function pct(v,d){var n=prob(v);return n===null?"—":(n*100).toFixed(d==null?0:d)+"%"}
  function pctRaw(v,d){var n=num(v);return n===null?"—":n.toFixed(d==null?0:d)+"%"}
  function initials(v){return String(v||"?").trim().split(/\s+/).slice(0,2).map(function(p){return p.charAt(0)}).join("").toUpperCase()}
  function dateObj(v){if(!has(v))return null;var d=new Date(v);return isNaN(d.getTime())?null:d}
  function dateText(v){var d=dateObj(v);return d?d.toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"}):String(v||"Date TBD")}
  function ageText(v){var d=dateObj(v);if(!d)return"time not published";var s=Math.max(0,(Date.now()-d.getTime())/1000);if(s<90)return"just now";if(s<3600)return Math.floor(s/60)+"m ago";if(s<86400)return Math.floor(s/3600)+"h ago";return Math.floor(s/86400)+"d ago"}
  function rows(p,keys){if(Array.isArray(p))return p;for(var i=0;i<keys.length;i++){var v=p&&p[keys[i]];if(Array.isArray(v))return v;if(v&&typeof v==="object")return Object.keys(v).map(function(k){return Object.assign({key:k},v[k]||{})})}return[]}
  function load(path){return fetch(path,{cache:"no-store"}).then(function(r){if(!r.ok)throw new Error(path+" "+r.status);return r.json()}).catch(function(e){console.warn(e);return{}})}
  function currentFile(){return location.pathname.split("/").pop()||"index.html"}
  function pageGroup(){return document.body.dataset.section||GROUPS[currentFile()]||""}
  function safeHref(v){var s=String(v||"");return s&&!/^javascript:/i.test(s)?esc(s):"#"}

  function installShell(){
    if($("hw-shell"))return;
    document.body.classList.add("hw-product");
    var group=pageGroup(),header=document.createElement("header");header.id="hw-shell";header.className="hw-topbar";
    var nav=NAV.map(function(n){return'<a href="'+n[2]+'"'+(n[0]===group?' aria-current="page"':'')+'>'+n[1]+'</a>'}).join("");
    var more=MORE.map(function(n){return'<a href="'+n[1]+'"><span>'+n[0]+'</span><small>'+n[2]+'</small></a>'}).join("");
    header.innerHTML='<div class="hw-topbar-inner"><a class="hw-brand" href="index.html"><span class="hw-brand-mark">H</span><span>Hardwood</span></a><button class="hw-menu-button" id="hw-menu-button" type="button" aria-expanded="false" aria-controls="hw-nav">☰</button><nav class="hw-nav" id="hw-nav" aria-label="Primary">'+nav+'<details class="hw-more"><summary>More</summary><div class="hw-more-menu">'+more+'</div></details></nav></div>';
    document.body.insertBefore(header,document.body.firstChild);
    var button=$("hw-menu-button"),navEl=$("hw-nav");if(button&&navEl)button.addEventListener("click",function(){var open=navEl.classList.toggle("open");button.setAttribute("aria-expanded",String(open));button.textContent=open?"×":"☰"});
    document.addEventListener("click",function(e){qa(".hw-more[open]").forEach(function(d){if(!d.contains(e.target))d.removeAttribute("open")})});
    var footer=document.createElement("footer");footer.className="hw-footer";footer.innerHTML='<div class="hw-footer-inner"><div><strong>Hardwood</strong>WNBA predictions, player intelligence, public grading, and research.</div><div class="hw-footer-links"><a href="games.html">Games</a><a href="players.html">Players</a><a href="teams.html">Teams</a><a href="standings.html">Standings</a><a href="accuracy.html">Accuracy</a><a href="deepdive.html">Research</a><a href="report_archive.html">Reports</a><a href="primer.html">Methodology</a><a href="board.html">Operations</a></div></div>';document.body.appendChild(footer)
  }
  function setFresh(payloads){var stamps=[];(payloads||[]).forEach(function(p){["generated_utc","generated","built_utc","updated_utc","as_of"].some(function(k){var d=dateObj(p&&p[k]);if(d){stamps.push(d);return true}return false})});stamps.sort(function(a,b){return b-a});qa("[data-fresh]").forEach(function(el){var d=stamps[0];if(!d){el.classList.add("warn");el.innerHTML='<span class="hw-fresh-dot"></span>Build time unavailable';return}var h=(Date.now()-d.getTime())/36e5;el.classList.toggle("warn",h>24);el.innerHTML='<span class="hw-fresh-dot"></span>Updated '+ageText(d.toISOString())})}
  function spark(vals){var a=(vals||[]).map(num).filter(function(v){return v!==null});if(a.length<2)return"—";var min=Math.min.apply(null,a),max=Math.max.apply(null,a),span=max-min||1,pts=a.map(function(v,i){return(i/(a.length-1)*74+1).toFixed(1)+","+(22-(v-min)/span*20+1).toFixed(1)}).join(" ");return'<svg class="hw-spark" viewBox="0 0 76 24" role="img" aria-label="Recent trend"><polyline points="'+pts+'"></polyline></svg>'}

  function normGames(payload,preview){var list=rows(payload,["games","rows","items"]),pr=rows(preview,["games","rows","items"]),map={};pr.forEach(function(p){var id=String(first(p,["game_id","id","key"])||"");if(id)map[id]=p});return list.map(function(g){var id=String(first(g,["game_id","id","key"])||""),pv=map[id]||{},pred=g.predictions&&typeof g.predictions==="object"?g.predictions:{},home=first(g,["home","home_team","home_abbr"])||first(pv,["home","home_team","home_abbr"]),away=first(g,["away","away_team","away_abbr"])||first(pv,["away","away_team","away_abbr"]),margin=first(g,["pred_margin","predicted_margin","projected_margin"]);if(!has(margin))margin=first(pred,["predicted_margin","point_spread","projected_margin"]);var total=first(g,["total","pred_total","predicted_total"]);if(!has(total))total=first(pred,["predicted_total","total","projected_total"]);var hp=first(g,["p_home_win","home_win_probability","home_probability"]);if(!has(hp))hp=first(pred,["home_win_probability","home_probability"]);var call=first(g,["call","predicted_winner"])||first(pred,["winner","predicted_winner","pick"]);var lo=first(g,["range80_lo"]),hi=first(g,["range80_hi"]),actual=num(first(g,["actual_margin","home_margin"])),hs=num(first(g,["home_score","actual_home_score"])),as=num(first(g,["away_score","actual_away_score"]));if(actual===null&&hs!==null&&as!==null)actual=hs-as;var status=first(g,["status","game_status"])||(g.awaiting_final?"Upcoming":actual!==null?"Final":"Scheduled");return{raw:g,id:id,date:first(g,["date","game_date","scheduled_at"]),tip:first(g,["tip_et","tip","time_et"]),home:String(home||"TBD"),away:String(away||"TBD"),margin:num(margin),total:num(total),homeP:prob(hp),call:call,status:String(status),lo:num(lo),hi:num(hi),actual:actual,model:String(first(g,["model_version","source_model","source_version"])||first(pred,["source_model","model_version","source_version"])||"published model"),outs:g.avail&&g.avail.home&&g.avail.away?[].concat(g.avail.home.out||[],g.avail.away.out||[]):[],report:"game_report_v2.html?game_id="+encodeURIComponent(id)}})}
  function normPlayers(p){var source=p&&p.ratings&&Array.isArray(p.ratings.players)?p.ratings.players:rows(p,["players","ratings","rows","items"]);return source.map(function(x,i){return{id:first(x,["id","player_id","nba_player_id"]),name:String(first(x,["name","player_name","canonical_name"])||"Unknown player"),team:String(first(x,["team","team_abbr"])||"—"),rank:num(x.rank)||i+1,impact:num(first(x,["rating","impact","impact_rating"])),impactRank:num(x.impact_rank),minutes:num(first(x,["minutes","predicted_minutes","min_avg"])),gp:num(first(x,["gp","games"])),pts:num(first(x,["pts","points"])),reb:num(first(x,["reb","rebounds"])),ast:num(first(x,["ast","assists"])),basis:num(first(x,["n_basis","sample_games"])),provisional:Boolean(first(x,["impact_provisional","provisional","thin","small_basis"])),profile:first(x,["profile_url","player_url"])||("players/"+first(x,["id","player_id","nba_player_id"])+".html")}})}
  function normTeams(p,standings){var sm={};rows(standings,["teams","rows"]).forEach(function(s){sm[String(s.team||s.team_abbr)]=s});return rows(p,["teams","rows"]).map(function(t,i){var s=sm[String(t.team||t.team_abbr)]||{};return{rank:num(t.rank)||i+1,team:String(t.team||t.team_abbr||"—"),name:String(t.team_full||t.name||t.team||"Unknown team"),strength:num(t.strength),churn:num(t.churn),title:num(t.title_pct),playoff:num(t.playoff_pct),trend:t.trend||{},wins:num(s.wins),losses:num(s.losses),proj:num(s.proj_median_wins),range:s.proj_range_90,pTitle:prob(s.p_title),pPlayoff:prob(s.p_playoff)}})}
  function normStandings(p){return rows(p,["teams","rows"]).map(function(s,i){return{rank:i+1,team:String(s.team||"—"),name:String(s.team_full||s.team||"Unknown team"),conf:s.conference,wins:num(s.wins),losses:num(s.losses),pct:num(s.win_pct),gb:num(s.games_back),proj:num(s.proj_median_wins),range:s.proj_range_90,playoff:prob(s.p_playoff),title:prob(s.p_title)}})}
  function gameCard(g){var hp=g.homeP,ap=hp===null?null:1-hp;return'<article class="hw-card hw-game"><div class="hw-game-meta"><span>'+esc(dateText(g.date))+'</span><span>'+esc(g.tip||g.status)+'</span></div><div class="hw-matchup"><div class="hw-team"><strong>'+esc(g.away)+'</strong><span>'+(ap===null?'Away':pct(ap)+' win')+'</span></div><span class="hw-at">@</span><div class="hw-team"><strong>'+esc(g.home)+'</strong><span>'+(hp===null?'Home':pct(hp)+' win')+'</span></div></div><div><div class="hw-prob-labels"><span>'+esc(g.away)+'</span><span>'+esc(g.home)+'</span></div><div class="hw-prob"><span style="width:'+(hp===null?50:Math.max(2,Math.min(98,hp*100)))+'%"></span></div></div><div class="hw-game-stats"><div class="hw-game-stat"><strong>'+esc(signed(g.margin))+'</strong><span>home margin</span></div><div class="hw-game-stat"><strong>'+esc(fixed(g.total,1))+'</strong><span>total</span></div><div class="hw-game-stat"><strong>'+(g.lo!==null&&g.hi!==null?esc(signed(g.lo)+"–"+signed(g.hi)):"—")+'</strong><span>80% range</span></div></div><div class="hw-row-end"><span class="hw-model">'+esc(g.model)+'</span><a class="hw-button" href="'+safeHref(g.report)+'">Full report</a></div></article>'}
  function personCell(p){return'<a class="hw-person" href="'+safeHref(p.profile)+'"><span class="hw-avatar">'+esc(initials(p.name))+'</span><span class="hw-person-copy"><strong>'+esc(p.name)+'</strong><small>'+esc(p.team)+'</small></span></a>'}

  function renderHome(){Promise.all([load("games.json"),load("preview.json"),load("players.json"),load("standings.json"),load("deepdive.json"),load("accuracy.json")]).then(function(a){var games=normGames(a[0],a[1]),players=normPlayers(a[2]),stand=normStandings(a[3]),dives=rows(a[4],["items","rows"]),surfaces=rows(a[5],["surfaces"]);setFresh(a);var k=$("home-kpis");if(k)k.innerHTML=[['Published games',games.length.toLocaleString(),'forecast archive'],['Rated players',players.length.toLocaleString(),'current leaderboard'],['Margin MAE',surfaces.length?fixed(surfaces[0].value,1):'—','public grade'],['Research notes',dives.length.toLocaleString(),'tested ideas']].map(function(x){return'<div class="hw-kpi"><span class="hw-kpi-label">'+x[0]+'</span><strong class="hw-kpi-value">'+x[1]+'</strong><span class="hw-kpi-note">'+x[2]+'</span></div>'}).join("");var now=Date.now()-18*36e5,up=games.filter(function(g){var d=dateObj(g.date);return d&&d.getTime()>=now}).sort(function(x,y){return dateObj(x.date)-dateObj(y.date)}).slice(0,6);if(!up.length)up=games.slice(-3).reverse();$("home-games").innerHTML=up.length?up.map(gameCard).join(""):'<div class="hw-card hw-empty">No current game forecasts are published.</div>';players.sort(function(x,y){return(y.impact===null?-999:y.impact)-(x.impact===null?-999:x.impact)});$("home-players").innerHTML=players.slice(0,10).map(function(p,i){return'<tr><td class="hw-rank">'+(i+1)+'</td><td>'+personCell(p)+'</td><td class="num '+(p.impact>=0?'hw-positive':'hw-negative')+'">'+signed(p.impact,2)+'</td><td class="num">'+fixed(p.minutes,1)+'</td><td class="num">'+fixed(p.pts,1)+'</td></tr>'}).join("");$("home-standings").innerHTML=stand.slice(0,10).map(function(s){return'<tr><td class="hw-rank">'+s.rank+'</td><td><strong>'+esc(s.team)+'</strong><br><small class="hw-muted">'+esc(s.name)+'</small></td><td class="num">'+fixed(s.wins,0)+'–'+fixed(s.losses,0)+'</td><td class="num">'+fixed(s.proj,1)+'</td><td class="num">'+pct(s.playoff)+'</td><td class="num">'+pct(s.title,1)+'</td></tr>'}).join("");$("home-research").innerHTML=dives.slice(0,6).map(researchCard).join("")})}
  function renderGames(){Promise.all([load("games.json"),load("preview.json")]).then(function(a){state.games=normGames(a[0],a[1]);setFresh(a);var teams={};state.games.forEach(function(g){teams[g.home]=1;teams[g.away]=1});var sel=$("game-team");if(sel)sel.innerHTML='<option value="">All teams</option>'+Object.keys(teams).sort().map(function(t){return'<option>'+esc(t)+'</option>'}).join("");["game-search","game-team","game-status"].forEach(function(id){var e=$(id);if(e)e.addEventListener(id==="game-search"?"input":"change",drawGames)});drawGames()})}
  function drawGames(){var q=($("game-search")&&$("game-search").value||"").toLowerCase(),team=$("game-team")&&$("game-team").value,status=$("game-status")&&$("game-status").value;var list=(state.games||[]).filter(function(g){return(!q||(g.home+" "+g.away+" "+g.call).toLowerCase().includes(q))&&(!team||g.home===team||g.away===team)&&(!status||g.status.toLowerCase().includes(status.toLowerCase()))}).sort(function(a,b){return(dateObj(b.date)||0)-(dateObj(a.date)||0)});var count=$("game-count");if(count)count.textContent=list.length+" games";$("games-grid").innerHTML=list.length?list.map(gameCard).join(""):'<div class="hw-card hw-empty">No games match these filters.</div>'}
  function renderPlayers(){load("players.json").then(function(p){state.players=normPlayers(p);setFresh([p]);["player-search","player-team","player-sort"].forEach(function(id){var e=$(id);if(e)e.addEventListener(id==="player-search"?"input":"change",drawPlayers)});var teams={};state.players.forEach(function(x){teams[x.team]=1});$("player-team").innerHTML='<option value="">All teams</option>'+Object.keys(teams).sort().map(function(t){return'<option>'+esc(t)+'</option>'}).join("");drawPlayers()})}
  function drawPlayers(){var q=($("player-search").value||"").toLowerCase(),team=$("player-team").value,sort=$("player-sort").value||"impact";var a=(state.players||[]).filter(function(p){return(!q||(p.name+" "+p.team).toLowerCase().includes(q))&&(!team||p.team===team)});a.sort(function(x,y){if(sort==="name")return x.name.localeCompare(y.name);return(y[sort]===null?-999:y[sort])-(x[sort]===null?-999:x[sort])});$("player-count").textContent=a.length+" players";$("players-table").innerHTML=a.map(function(p,i){return'<tr><td class="hw-rank">'+(i+1)+'</td><td>'+personCell(p)+'</td><td class="num '+(p.impact>=0?'hw-positive':'hw-negative')+'">'+signed(p.impact,2)+'</td><td class="num">'+fixed(p.minutes,1)+'</td><td class="num">'+fixed(p.pts,1)+'</td><td class="num">'+fixed(p.reb,1)+'</td><td class="num">'+fixed(p.ast,1)+'</td><td class="num">'+fixed(p.gp,0)+'</td><td>'+(p.provisional?'<span class="hw-badge warn">provisional</span>':'<span class="hw-badge good">established</span>')+'</td></tr>'}).join("")}
  function renderTeams(){Promise.all([load("teams.json"),load("standings.json")]).then(function(a){state.teams=normTeams(a[0],a[1]);setFresh(a);var s=$("team-search");if(s)s.addEventListener("input",drawTeams);drawTeams()})}
  function drawTeams(){var q=($("team-search")&&$("team-search").value||"").toLowerCase(),a=(state.teams||[]).filter(function(t){return!q||(t.team+" "+t.name).toLowerCase().includes(q)});$("team-count").textContent=a.length+" teams";$("teams-table").innerHTML=a.map(function(t){var range=Array.isArray(t.range)?fixed(t.range[0],1)+"–"+fixed(t.range[1],1):"—";return'<tr><td class="hw-rank">'+t.rank+'</td><td><strong>'+esc(t.team)+'</strong><br><small class="hw-muted">'+esc(t.name)+'</small></td><td class="num '+(t.strength>=0?'hw-positive':'hw-negative')+'">'+signed(t.strength,1)+'</td><td>'+spark(t.trend.strength)+'</td><td class="num">'+(t.wins===null?'—':fixed(t.wins,0)+'–'+fixed(t.losses,0))+'</td><td class="num">'+fixed(t.proj,1)+'</td><td class="num">'+range+'</td><td class="num">'+(t.pPlayoff!==null?pct(t.pPlayoff):pctRaw(t.playoff))+'</td><td class="num">'+(t.pTitle!==null?pct(t.pTitle,1):pctRaw(t.title,1))+'</td></tr>'}).join("")}
  function renderStandings(){load("standings.json").then(function(p){var a=normStandings(p);setFresh([p]);var prog=p.progress||{};$("standings-kpis").innerHTML=[['Season complete',has(prog.pct_complete)?prog.pct_complete+'%':'—','through '+(prog.standings_asof||'latest results')],['Games played',fixed(prog.games_played,0),'of '+fixed(prog.games_total,0)],['Games left',fixed(prog.games_unplayed,0),'regular season'],['Final date',dateText(prog.final_date),'scheduled finish']].map(function(x){return'<div class="hw-kpi"><span class="hw-kpi-label">'+x[0]+'</span><strong class="hw-kpi-value">'+x[1]+'</strong><span class="hw-kpi-note">'+x[2]+'</span></div>'}).join("");$("standings-table").innerHTML=a.map(function(s){var range=Array.isArray(s.range)?fixed(s.range[0],1)+"–"+fixed(s.range[1],1):"—";return'<tr><td class="hw-rank">'+s.rank+'</td><td><strong>'+esc(s.team)+'</strong><br><small class="hw-muted">'+esc(s.name)+'</small></td><td>'+esc(s.conf||'—')+'</td><td class="num">'+fixed(s.wins,0)+'–'+fixed(s.losses,0)+'</td><td class="num">'+fixed(s.pct,3)+'</td><td class="num">'+fixed(s.gb,1)+'</td><td class="num">'+fixed(s.proj,1)+'</td><td class="num">'+range+'</td><td class="num">'+pct(s.playoff)+'</td><td class="num">'+pct(s.title,1)+'</td></tr>'}).join("")})}
  function researchSummary(item){var c=Array.isArray(item.content)?item.content:[];for(var i=0;i<c.length;i++){var s=String(c[i]||"").replace(/^#+\s*/,"").replace(/\*\*/g,"");if(s&&s!==item.title&&!/^Record:/i.test(s)&&!/^```/.test(s)&&!/^###/.test(s))return s}return"Open the research note for the measured result and decision."}
  function researchCard(item){return'<article class="hw-card hw-research"><div class="hw-research-meta"><span>'+esc(dateText(item.as_of))+'</span><span class="hw-badge">research</span></div><h3>'+esc(item.title||'Untitled research')+'</h3><p>'+esc(researchSummary(item))+'</p><a class="hw-section-link" href="deepdive.html?q='+encodeURIComponent(item.title||'')+'">Read finding →</a></article>'}
  function renderResearch(){load("deepdive.json").then(function(p){state.research=rows(p,["items","rows"]);setFresh([p]);var q=$("research-search");if(q){var preset=new URLSearchParams(location.search).get("q");if(preset)q.value=preset;q.addEventListener("input",drawResearch)}drawResearch()})}
  function drawResearch(){var q=($("research-search").value||"").toLowerCase(),a=(state.research||[]).filter(function(x){return!q||(x.title+" "+(x.content||[]).join(" ")).toLowerCase().includes(q)});$("research-count").textContent=a.length+" notes";$("research-grid").innerHTML=a.length?a.map(researchCard).join(""):'<div class="hw-card hw-empty">No research notes match this search.</div>'}
  function renderAccuracy(){load("accuracy.json").then(function(p){setFresh([p]);var surfaces=rows(p,["surfaces"]),cal=rows(p,["calibration"]),monthly=rows(p,["monthly"]);$("accuracy-kpis").innerHTML=surfaces.map(function(s){return'<div class="hw-kpi"><span class="hw-kpi-label">'+esc(s.surface)+'</span><strong class="hw-kpi-value">'+(s.no_data?'—':esc(fixed(s.value,2)))+(s.unit==='%'?'<small>%</small>':'')+'</strong><span class="hw-kpi-note">n='+esc(s.n||0)+' · '+esc(s.direction||'')+'</span></div>'}).join("");$("accuracy-calibration").innerHTML=cal.length?cal.map(function(c){var actual=num(c.actual),target=num(c.target),width=actual===null?0:Math.max(0,Math.min(100,actual));return'<div class="hw-cal-row"><div class="hw-cal-top"><strong>'+esc(c.surface)+'</strong><span>'+fixed(actual,1)+'% actual · '+fixed(target,0)+'% target · n='+esc(c.n||0)+'</span></div><div class="hw-cal-bar"><span style="width:'+width+'%"></span></div></div>'}).join(""):'<div class="hw-empty">Calibration is not published yet.</div>';$("accuracy-monthly").innerHTML=monthly.map(function(m){return'<tr><td>'+esc(m.month)+'</td><td class="num">'+fixed(m.value,2)+'</td><td class="num">'+esc(m.n||0)+'</td></tr>'}).join("")})}

  function boot(){installShell();var p=document.body.dataset.page||pageGroup();if(p==="home")renderHome();else if(p==="games")renderGames();else if(p==="players")renderPlayers();else if(p==="teams")renderTeams();else if(p==="standings")renderStandings();else if(p==="research")renderResearch();else if(p==="accuracy")renderAccuracy()}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot);else boot();
})();
