/* Dense Reports: immutable forecast archive joined to factual finals for grading. */
(function(){
  "use strict";

  var FILES={archive:"report_archive.json",finals:"finals.json",teams:"teams.json"};
  var state={records:[],filtered:[],days:[],selected:null,viz:"confidence-miss",payloads:{}};
  var $=function(id){return document.getElementById(id);};
  var qa=function(selector,root){return Array.prototype.slice.call((root||document).querySelectorAll(selector));};
  var has=function(value){return value!==null&&value!==undefined&&value!=="";};
  var num=function(value){if(value===true||value===false||value===null||value===undefined||value==="")return null;var parsed=Number(value);return Number.isFinite(parsed)?parsed:null;};
  var esc=function(value){return String(value==null?"":value).replace(/[&<>"']/g,function(char){return {"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[char];});};
  var fixed=function(value,digits){var parsed=num(value);return parsed===null?"—":parsed.toFixed(digits==null?1:digits);};
  var signed=function(value,digits){var parsed=num(value);return parsed===null?"—":(parsed>0?"+":"")+parsed.toFixed(digits==null?1:digits);};
  var pct=function(value,digits){var parsed=num(value);if(parsed===null)return "—";if(parsed<=1)parsed*=100;return parsed.toFixed(digits==null?0:digits)+"%";};
  var normalize=function(value){return String(value||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();};
  var truncText=function(value,max){var text=String(value||"").replace(/\s+/g," ").trim();return text.length>max?text.slice(0,max-1).trim()+"…":text;};
  var safeHref=function(value){var text=String(value||"");return text&&!/^javascript:/i.test(text)?esc(text):"#";};
  var parseDate=function(value){if(!has(value))return null;var text=String(value);var parsed=/^\d{4}-\d{2}-\d{2}$/.test(text)?new Date(text+"T12:00:00"):new Date(text);return Number.isNaN(parsed.getTime())?null:parsed;};
  var dateText=function(value){var parsed=parseDate(value);return parsed?parsed.toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"}):String(value||"—");};
  var shortDate=function(value){var parsed=parseDate(value);return parsed?parsed.toLocaleDateString(undefined,{month:"short",day:"numeric"}):String(value||"—");};
  var monthKey=function(value){var parsed=parseDate(value);return parsed?parsed.getFullYear()+"-"+String(parsed.getMonth()+1).padStart(2,"0"):"";};
  var monthLabel=function(key){var parsed=parseDate(key+"-01");return parsed?parsed.toLocaleDateString(undefined,{month:"long",year:"numeric"}):key;};
  var rows=function(payload,keys){if(Array.isArray(payload))return payload;for(var index=0;index<keys.length;index++){var value=payload&&payload[keys[index]];if(Array.isArray(value))return value;}return [];};
  var fetchJSON=function(path){return fetch(path,{cache:"no-store"}).then(function(response){if(!response.ok)throw new Error(path+" returned "+response.status);return response.json();});};
  var matchupKey=function(date,matchup){return String(date||"")+"|"+String(matchup||"").toUpperCase().replace(/\s+/g," ").trim();};

  function teamMaps(payload){
    var byCode={},byName={};
    rows(payload,["teams","rows","items"]).forEach(function(team){
      var code=String(team.team||team.team_abbr||team.abbr||"").toUpperCase(),name=String(team.team_full||team.team_name||team.name||"");
      if(!code)return;byCode[code]=name||code;byName[normalize(code)]=code;if(name)byName[normalize(name)]=code;
    });
    var fallback={ATL:"Atlanta Dream",CHI:"Chicago Sky",CON:"Connecticut Sun",DAL:"Dallas Wings",GSV:"Golden State Valkyries",IND:"Indiana Fever",LAS:"Los Angeles Sparks",LVA:"Las Vegas Aces",MIN:"Minnesota Lynx",NYL:"New York Liberty",PHO:"Phoenix Mercury",POR:"Portland Fire",SEA:"Seattle Storm",TOR:"Toronto Tempo",WAS:"Washington Mystics"};
    Object.keys(fallback).forEach(function(code){if(!byCode[code])byCode[code]=fallback[code];byName[normalize(code)]=code;byName[normalize(fallback[code])]=code;});
    return {byCode:byCode,byName:byName};
  }

  function resolveTeam(value,maps){
    var key=normalize(value);if(!key)return null;if(maps.byName[key])return maps.byName[key];
    var codes=Object.keys(maps.byCode).sort(function(a,b){return b.length-a.length;});
    for(var index=0;index<codes.length;index++){
      var code=codes[index],name=normalize(maps.byCode[code]);
      if(key===normalize(code)||key===name||key.indexOf(name)>=0||name.indexOf(key)>=0)return code;
    }
    return null;
  }

  function splitMatchup(value){var parts=String(value||"").split(/\s+@\s+/);return {away:String(parts[0]||"").toUpperCase().trim(),home:String(parts[1]||"").toUpperCase().trim()};}
  function parseCall(call,matchup,maps){
    var text=String(call||"").trim(),amountMatch=text.match(/\bby\s+([0-9]+(?:\.[0-9]+)?)/i),winnerText=amountMatch?text.slice(0,amountMatch.index).trim():text.replace(/\bto win.*$/i,"").trim(),winner=resolveTeam(winnerText,maps),amount=amountMatch?num(amountMatch[1]):null;
    if(amount===null&&/even|pick(?:'|’)em/i.test(text))amount=0;
    var homeMargin=amount===null||!winner?null:winner===matchup.home?Math.abs(amount):winner===matchup.away?-Math.abs(amount):null;
    return {winner:winner,homeMargin:homeMargin};
  }
  function parseRange(text,matchup,maps){
    var match=String(text||"").match(/^(.+?)\s+by\s+([0-9]+(?:\.[0-9]+)?)\s+to\s+(.+?)\s+by\s+([0-9]+(?:\.[0-9]+)?)$/i);
    if(!match)return null;
    function endpoint(teamText,amountText){var team=resolveTeam(teamText,maps),amount=num(amountText);if(team===matchup.home)return Math.abs(amount);if(team===matchup.away)return -Math.abs(amount);return null;}
    var first=endpoint(match[1],match[2]),second=endpoint(match[3],match[4]);if(first===null||second===null)return null;return [Math.min(first,second),Math.max(first,second)];
  }

  function normalizeFinals(payload){var map={};rows(payload,["games","rows","items"]).forEach(function(final){var matchup=final.matchup||((final.away||final.away_team)+" @ "+(final.home||final.home_team));map[matchupKey(final.date||final.game_date,matchup)]={away:String(final.away||final.away_team||"").toUpperCase(),home:String(final.home||final.home_team||"").toUpperCase(),awayScore:num(final.away_score),homeScore:num(final.home_score),homeMargin:num(final.home_margin),winner:String(final.winner||"").toUpperCase(),final:final.final||null};});return map;}

  function normalizeArchive(archivePayload,finalsPayload,teamsPayload){
    var maps=teamMaps(teamsPayload),finalMap=normalizeFinals(finalsPayload),records=[],dayRows=[];
    rows(archivePayload,["days","rows","items"]).forEach(function(day){
      var reportMap={};(day.reports||[]).forEach(function(report){reportMap[String(report.label||"").toUpperCase().replace(/\s+/g," ").trim()]=report.href;});
      var daily=[];(day.predictions||[]).forEach(function(prediction,index){
        var matchupText=String(prediction.matchup||""),matchup=splitMatchup(matchupText),parsedCall=parseCall(prediction.call,matchup,maps),range=parseRange(prediction.range80,matchup,maps),final=finalMap[matchupKey(day.date,matchupText)]||null,report=reportMap[matchupText.toUpperCase().replace(/\s+/g," ").trim()]||null,actual=final&&final.homeMargin!==null?final.homeMargin:null,miss=actual!==null&&parsedCall.homeMargin!==null?Math.abs(actual-parsedCall.homeMargin):null,correct=final&&parsedCall.winner?final.winner===parsedCall.winner:null,covered=actual!==null&&range?actual>=range[0]&&actual<=range[1]:null;
        var record={id:String(day.date)+"|"+matchupText+"|"+index,date:day.date,tip:prediction.tip||null,matchup:matchupText,away:matchup.away,home:matchup.home,awayFull:maps.byCode[matchup.away]||matchup.away,homeFull:maps.byCode[matchup.home]||matchup.home,call:prediction.call||"Call not published",winLine:prediction.win_line||null,winPct:num(prediction.win_pct),rangeText:prediction.range80||null,range:range,predictedWinner:parsedCall.winner,predictedHomeMargin:parsedCall.homeMargin,final:final,actualHomeMargin:actual,miss:miss,correct:correct,rangeCovered:covered,report:report,month:monthKey(day.date)};
        records.push(record);daily.push(record);
      });
      var graded=daily.filter(function(record){return record.final;}),correct=graded.filter(function(record){return record.correct===true;}),misses=graded.map(function(record){return record.miss;}).filter(function(value){return value!==null;}),reports=daily.filter(function(record){return record.report;});
      dayRows.push({date:day.date,calls:daily.length,reports:reports.length,coverage:daily.length?reports.length/daily.length:null,graded:graded.length,correct:correct.length,accuracy:graded.length?correct.length/graded.length:null,avgMiss:misses.length?misses.reduce(function(sum,value){return sum+value;},0)/misses.length:null});
    });
    return {records:records,days:dayRows,maps:maps};
  }

  function gradeKey(record){if(!record.final)return "pending";return record.correct?"correct":"wrong";}
  function confidenceKey(record){if(record.winPct===null)return "unknown";if(record.winPct>=70)return "high";if(record.winPct>=55)return "mid";return "coin";}
  function filters(){return {search:normalize($("reports-search").value),team:$("reports-team").value,month:$("reports-month").value,grade:$("reports-grade").value,coverage:$("reports-coverage").value,confidence:$("reports-confidence").value,sort:$("reports-sort").value};}
  function applyFilters(){
    var f=filters();state.filtered=state.records.filter(function(record){
      if(f.search&&normalize(record.matchup+" "+record.call+" "+record.awayFull+" "+record.homeFull).indexOf(f.search)<0)return false;
      if(f.team&&record.away!==f.team&&record.home!==f.team)return false;
      if(f.month&&record.month!==f.month)return false;
      if(f.grade&&gradeKey(record)!==f.grade)return false;
      if(f.coverage==="with"&&!record.report)return false;if(f.coverage==="without"&&record.report)return false;
      if(f.confidence&&confidenceKey(record)!==f.confidence)return false;
      return true;
    });
    state.filtered.sort(function(a,b){
      if(f.sort==="confidence")return (b.winPct===null?-1:b.winPct)-(a.winPct===null?-1:a.winPct)||String(b.date).localeCompare(String(a.date));
      if(f.sort==="miss")return (b.miss===null?-1:b.miss)-(a.miss===null?-1:a.miss)||String(b.date).localeCompare(String(a.date));
      if(f.sort==="closest")return Math.abs(a.predictedHomeMargin===null?999:a.predictedHomeMargin)-Math.abs(b.predictedHomeMargin===null?999:b.predictedHomeMargin)||String(b.date).localeCompare(String(a.date));
      if(f.sort==="date-asc")return String(a.date).localeCompare(String(b.date))||a.matchup.localeCompare(b.matchup);
      return String(b.date).localeCompare(String(a.date))||a.matchup.localeCompare(b.matchup);
    });
  }

  function gradeBadge(record){if(!record.final)return '<span class="hw-report-grade pending">Pending</span>';return record.correct?'<span class="hw-report-grade correct">Correct</span>':'<span class="hw-report-grade wrong">Wrong</span>';}
  function rangeHTML(record){if(!record.range)return '<span class="hw-muted">'+esc(record.rangeText||"—")+'</span>';return '<span class="hw-report-range"><span>'+esc(signed(record.range[0],0))+'</span><i><b style="left:'+Math.max(0,Math.min(100,(record.predictedHomeMargin-record.range[0])/(record.range[1]-record.range[0])*100)).toFixed(1)+'%"></b></i><span>'+esc(signed(record.range[1],0))+'</span></span>';}
  function tableRow(record){var selected=state.selected&&state.selected.id===record.id;return '<tr'+(selected?' class="selected"':'')+'><td><span class="hw-report-date"><strong>'+esc(shortDate(record.date))+'</strong><small>'+esc(record.tip||"time not published")+'</small></span></td><td><button class="hw-report-select" type="button" data-select-report="'+esc(record.id)+'"><strong>'+esc(record.matchup)+'</strong><small>'+esc(record.awayFull+' @ '+record.homeFull)+'</small></button></td><td>'+esc(record.call)+'</td><td class="num">'+esc(record.winPct===null?'—':record.winPct.toFixed(0)+'%')+'</td><td>'+rangeHTML(record)+'</td><td>'+esc(record.final?(record.final.homeScore!==null&&record.final.awayScore!==null?record.final.awayScore+'–'+record.final.homeScore:(record.final.final||"Final")):"—")+'</td><td class="num">'+esc(signed(record.actualHomeMargin,1))+'</td><td class="num">'+esc(fixed(record.miss,1))+'</td><td>'+gradeBadge(record)+'</td><td>'+(record.report?'<a class="hw-link" href="'+safeHref(record.report)+'" target="_blank" rel="noopener">PDF ↗</a>':'<span class="hw-muted">—</span>')+'</td></tr>';}
  function mobileRow(record){var selected=state.selected&&state.selected.id===record.id;return '<button type="button" class="hw-mobile-report'+(selected?' selected':'')+'" data-select-report="'+esc(record.id)+'"><span class="hw-mobile-report-top"><strong>'+esc(record.matchup)+'</strong><span>'+esc(shortDate(record.date))+' · '+esc(record.tip||"time TBD")+'</span></span><span class="hw-mobile-report-call">'+esc(record.call)+' · '+esc(record.winPct===null?'confidence not published':record.winPct.toFixed(0)+'%')+'</span><span class="hw-mobile-report-metrics"><span>Final<b>'+esc(record.final?(record.final.awayScore+'–'+record.final.homeScore):'—')+'</b></span><span>Margin<b>'+esc(signed(record.actualHomeMargin,1))+'</b></span><span>Miss<b>'+esc(fixed(record.miss,1))+'</b></span><span>Report<b>'+esc(record.report?'PDF':'—')+'</b></span></span><span class="hw-mobile-report-bottom">'+gradeBadge(record)+'<span>'+esc(record.rangeText||"range not published")+'</span></span></button>';}
  function bindSelections(){qa("[data-select-report]").forEach(function(button){button.addEventListener("click",function(){selectRecord(button.getAttribute("data-select-report"),true);});});}
  function renderBoard(){applyFilters();$("reports-count").textContent=state.filtered.length+" of "+state.records.length+" calls";$("reports-context").textContent=filters().sort+" · "+(filters().month?monthLabel(filters().month):"all dates");$("reports-body").innerHTML=state.filtered.map(tableRow).join("")||'<tr><td colspan="10"><div class="hw-empty">No archived calls match these filters.</div></td></tr>';$("reports-mobile").innerHTML=state.filtered.map(mobileRow).join("")||'<div class="hw-empty">No archived calls match these filters.</div>';bindSelections();}

  function metric(label,value,note){return '<div class="hw-report-inspector-metric"><span>'+esc(label)+'</span><strong>'+esc(value)+'</strong><small>'+esc(note||"")+'</small></div>';}
  function renderInspector(record){if(!record)return;var matchup=record.awayFull+' at '+record.homeFull,finalText=record.final?(record.final.final||record.awayFull+' '+record.final.awayScore+', '+record.homeFull+' '+record.final.homeScore):"Final not published",rangeVerdict=record.rangeCovered===null?"Not gradable":record.rangeCovered?"Inside 80% range":"Outside 80% range";$("report-inspector").innerHTML='<div class="hw-module-head"><h2>Report inspector</h2><span>'+esc(dateText(record.date))+'</span></div><div class="hw-report-inspector-body"><div class="hw-report-inspector-hero"><div><span class="hw-report-record">Immutable pre-tip record</span><h3>'+esc(matchup)+'</h3><p>'+esc(record.tip||"Tip time not published")+'</p></div>'+gradeBadge(record)+'</div><div class="hw-report-inspector-metrics">'+metric("Published call",record.call,record.predictedWinner||"winner not parsed")+metric("Win chance",record.winPct===null?"Not published":record.winPct.toFixed(0)+"%",record.winLine||"no win line")+metric("Home margin",signed(record.predictedHomeMargin,1),"positive favors home")+metric("80% range",record.rangeText||"Not published",rangeVerdict)+metric("Final",finalText,record.final?"factual result":"awaiting result")+metric("Margin miss",fixed(record.miss,1),record.miss===null?"not gradable":"absolute error")+'</div><section class="hw-report-inspector-section"><h3>Prediction versus result</h3><div class="hw-report-comparison"><div><span>Forecast home margin</span><strong>'+esc(signed(record.predictedHomeMargin,1))+'</strong></div><i>→</i><div><span>Actual home margin</span><strong>'+esc(signed(record.actualHomeMargin,1))+'</strong></div></div><p>'+esc(record.final?(record.correct?"The published winner call was correct.":"The published winner call was wrong."):"A final result has not been joined to this immutable call.")+'</p></section><section class="hw-report-inspector-section"><h3>Published uncertainty</h3><div class="hw-report-band">'+rangeHTML(record)+'</div><p>'+esc(record.rangeCovered===null?"The published range cannot be graded from the available fields.":record.rangeCovered?"The final home margin landed inside the published 80% range.":"The final home margin landed outside the published 80% range.")+'</p></section><section class="hw-report-inspector-section"><h3>Report product</h3>'+(record.report?'<a class="hw-report-pdf" href="'+safeHref(record.report)+'" target="_blank" rel="noopener"><strong>Open archived PDF</strong><span>'+esc(record.matchup+' · '+dateText(record.date))+' ↗</span></a>':'<div class="hw-empty compact">No gameday report PDF is archived for this prediction.</div>')+'</section><section class="hw-report-inspector-section"><h3>Record rule</h3><p>The forecast, confidence, and range come from the dated archive. The factual final is joined afterward only for grading; no prediction is recomputed on this page.</p></section></div>';}
  function selectRecord(id,scroll){var record=state.records.find(function(candidate){return candidate.id===id;});if(!record)return;state.selected=record;renderBoard();renderInspector(record);renderViz();if(scroll&&window.innerWidth<980)$("report-inspector").scrollIntoView({behavior:"smooth",block:"start"});}

  function story(label,value,note){return '<article class="hw-story"><span class="hw-story-label">'+esc(label)+'</span><strong class="hw-story-value">'+esc(value)+'</strong><span class="hw-story-note">'+esc(note)+'</span></article>';}
  function renderStories(){var reports=state.records.filter(function(record){return record.report;}),graded=state.records.filter(function(record){return record.final;}),correct=graded.filter(function(record){return record.correct;}),misses=graded.map(function(record){return record.miss;}).filter(function(value){return value!==null;}),covered=graded.filter(function(record){return record.rangeCovered===true;}),rangeGraded=graded.filter(function(record){return record.rangeCovered!==null;});$("reports-stories").innerHTML=[story("Archived calls",state.records.length.toLocaleString(),state.days.length+" slates"),story("Report PDFs",reports.length.toLocaleString(),state.records.length?Math.round(reports.length/state.records.length*100)+"% coverage":"coverage unavailable"),story("Graded calls",graded.length.toLocaleString(),state.records.length-graded.length+" awaiting finals"),story("Winner accuracy",graded.length?Math.round(correct.length/graded.length*100)+"%":"—",correct.length+" of "+graded.length),story("Average margin miss",misses.length?fixed(misses.reduce(function(sum,value){return sum+value;},0)/misses.length,1):"—",misses.length+" graded margins"),story("80% range coverage",rangeGraded.length?Math.round(covered.length/rangeGraded.length*100)+"%":"—",covered.length+" of "+rangeGraded.length)].join("");}

  function scale(value,domain,range){return range[0]+(value-domain[0])/(domain[1]-domain[0])*(range[1]-range[0]);}
  function extent(values,includeZero){var valid=values.filter(function(value){return num(value)!==null;});if(!valid.length)return [0,1];var min=Math.min.apply(null,valid),max=Math.max.apply(null,valid);if(includeZero){min=Math.min(min,0);max=Math.max(max,0);}if(min===max){min-=1;max+=1;}var pad=(max-min)*.1;return [min-pad,max+pad];}
  function scatter(records,xFn,yFn,xLabel,yLabel,xFormat,yFormat,diagonal){var points=records.filter(function(record){return xFn(record)!==null&&yFn(record)!==null;});if(!points.length)return '<div class="hw-empty">No archived calls carry both fields required for this visual.</div>';var width=820,height=285,left=58,right=24,top=18,bottom=42,xd=extent(points.map(xFn),true),yd=extent(points.map(yFn),true),sx=function(value){return scale(value,xd,[left,width-right]);},sy=function(value){return scale(value,yd,[height-bottom,top]);},out=['<svg viewBox="0 0 '+width+' '+height+'" role="img" aria-label="'+esc(xLabel+' versus '+yLabel)+'">'];[0,.25,.5,.75,1].forEach(function(q){var xv=xd[0]+q*(xd[1]-xd[0]),yv=yd[0]+q*(yd[1]-yd[0]),x=sx(xv),y=sy(yv);out.push('<line class="grid" x1="'+x+'" y1="'+top+'" x2="'+x+'" y2="'+(height-bottom)+'"></line><line class="grid" x1="'+left+'" y1="'+y+'" x2="'+(width-right)+'" y2="'+y+'"></line><text class="axis-label" x="'+x+'" y="'+(height-15)+'" text-anchor="middle">'+esc(xFormat(xv))+'</text><text class="axis-label" x="'+(left-7)+'" y="'+(y+3)+'" text-anchor="end">'+esc(yFormat(yv))+'</text>');});if(diagonal){var low=Math.max(xd[0],yd[0]),high=Math.min(xd[1],yd[1]);out.push('<line class="diagonal" x1="'+sx(low)+'" y1="'+sy(low)+'" x2="'+sx(high)+'" y2="'+sy(high)+'"></line>');}points.forEach(function(record){var selected=state.selected&&state.selected.id===record.id,good=record.correct===true,bad=record.correct===false;out.push('<g class="report-point '+(good?'correct':bad?'wrong':'pending')+(selected?' selected':'')+'" data-viz-report="'+esc(record.id)+'"><circle cx="'+sx(xFn(record)).toFixed(1)+'" cy="'+sy(yFn(record)).toFixed(1)+'" r="4"><title>'+esc(record.matchup+' · '+xLabel+' '+xFormat(xFn(record))+' · '+yLabel+' '+yFormat(yFn(record)))+'</title></circle></g>');});out.push('<text class="axis-label" x="'+((left+width-right)/2)+'" y="'+(height-2)+'" text-anchor="middle">'+esc(xLabel)+'</text><text class="axis-label" x="14" y="'+((top+height-bottom)/2)+'" transform="rotate(-90 14 '+((top+height-bottom)/2)+')" text-anchor="middle">'+esc(yLabel)+'</text></svg>');return out.join("");}
  function coverageBars(){var days=state.days.slice().sort(function(a,b){return String(a.date).localeCompare(String(b.date));}),max=Math.max.apply(null,days.map(function(day){return day.calls;}));return '<div class="hw-report-coverage-bars">'+days.map(function(day){var reportWidth=day.calls?day.reports/day.calls*100:0;return '<button type="button" data-filter-day="'+esc(day.date)+'"><span>'+esc(shortDate(day.date))+'</span><i><b style="width:'+reportWidth.toFixed(1)+'%"></b></i><strong>'+day.reports+'/'+day.calls+'</strong></button>';}).join("")+'</div>';}
  function renderViz(){var html,context;if(state.viz==="predicted-actual"){html=scatter(state.records,function(record){return record.predictedHomeMargin;},function(record){return record.actualHomeMargin;},"Predicted home margin","Actual home margin",function(value){return signed(value,0);},function(value){return signed(value,0);},true);context="Published home margin versus factual home margin";}else if(state.viz==="coverage"){html=coverageBars();context="Archived report-PDF coverage by slate";}else{html=scatter(state.records,function(record){return record.winPct;},function(record){return record.miss;},"Published win chance","Absolute margin miss",function(value){return fixed(value,0)+"%";},function(value){return fixed(value,0);},false);context="Published confidence versus absolute margin miss";}$("reports-viz-context").textContent=context;$("reports-viz").innerHTML=html;qa("[data-viz-report]").forEach(function(node){node.addEventListener("click",function(){selectRecord(node.getAttribute("data-viz-report"),true);});});qa("[data-filter-day]").forEach(function(node){node.addEventListener("click",function(){$("reports-month").value=monthKey(node.getAttribute("data-filter-day"));renderBoard();});});qa("[data-report-viz]").forEach(function(button){var active=button.getAttribute("data-report-viz")===state.viz;button.classList.toggle("active",active);button.setAttribute("aria-selected",active?"true":"false");});}

  function watchRow(record,value,note){return '<button type="button" class="hw-report-watch-row" data-select-report="'+esc(record.id)+'"><div><strong>'+esc(record.matchup+' · '+shortDate(record.date))+'</strong><small>'+esc(note)+'</small></div><span>'+esc(value)+'</span></button>';}
  function renderWatch(){var misses=state.records.filter(function(record){return record.miss!==null;}).sort(function(a,b){return b.miss-a.miss;}).slice(0,9),missing=state.records.filter(function(record){return !record.report;}).sort(function(a,b){return String(b.date).localeCompare(String(a.date));}).slice(0,9);$("reports-misses").innerHTML=misses.map(function(record){return watchRow(record,fixed(record.miss,1)+" pts",record.call+' · final '+signed(record.actualHomeMargin,1));}).join("")||'<div class="hw-empty compact">No graded margin misses were published.</div>';$("reports-missing").innerHTML=missing.map(function(record){return watchRow(record,"No PDF",record.call);}).join("")||'<div class="hw-empty compact">Every archived call has a report PDF.</div>';bindSelections();}
  function renderDays(){var days=state.days.slice().sort(function(a,b){return String(b.date).localeCompare(String(a.date));});$("reports-days-count").textContent=days.length+" slates";$("reports-days").innerHTML=days.map(function(day){return '<tr><td>'+esc(dateText(day.date))+'</td><td class="num">'+day.calls+'</td><td class="num">'+day.reports+'</td><td class="num">'+esc(pct(day.coverage,0))+'</td><td class="num">'+day.graded+'</td><td class="num">'+esc(pct(day.accuracy,0))+'</td><td class="num">'+esc(fixed(day.avgMiss,1))+'</td></tr>';}).join("")||'<tr><td colspan="7"><div class="hw-empty">No archived slates were published.</div></td></tr>';}

  function populateFilters(){var teams={},months={};state.records.forEach(function(record){teams[record.away]=true;teams[record.home]=true;months[record.month]=true;});$("reports-team").innerHTML='<option value="">All teams</option>'+Object.keys(teams).sort().map(function(team){return '<option value="'+esc(team)+'">'+esc(team)+'</option>';}).join("");$("reports-month").innerHTML='<option value="">All months</option>'+Object.keys(months).sort().reverse().map(function(month){return '<option value="'+esc(month)+'">'+esc(monthLabel(month))+'</option>';}).join("");}
  function bind(){["reports-team","reports-month","reports-grade","reports-coverage","reports-confidence","reports-sort"].forEach(function(id){$(id).addEventListener("change",renderBoard);});$("reports-search").addEventListener("input",renderBoard);$("reports-reset").addEventListener("click",function(){["reports-search","reports-team","reports-month","reports-grade","reports-coverage","reports-confidence"].forEach(function(id){$(id).value="";});$("reports-sort").value="newest";renderBoard();});qa("[data-report-viz]").forEach(function(button){button.addEventListener("click",function(){state.viz=button.getAttribute("data-report-viz");renderViz();});});}
  function setFreshness(payloads){var stamps=payloads.map(function(payload){return payload&&payload.generated_utc;}).map(parseDate).filter(Boolean).sort(function(a,b){return b-a;}),newest=stamps[0];qa("[data-fresh]").forEach(function(element){element.innerHTML='<span class="hw-fresh-dot"></span>'+(newest?'Built '+dateText(newest.toISOString()):'Build time not published');element.classList.toggle("warn",!newest);});}
  function boot(){Promise.all([fetchJSON(FILES.archive),fetchJSON(FILES.finals),fetchJSON(FILES.teams)]).then(function(payloads){state.payloads={archive:payloads[0],finals:payloads[1],teams:payloads[2]};var normalized=normalizeArchive(payloads[0],payloads[1],payloads[2]);state.records=normalized.records;state.days=normalized.days;populateFilters();setFreshness(payloads);bind();renderStories();renderWatch();renderDays();state.selected=state.records[0]||null;renderBoard();renderInspector(state.selected);renderViz();}).catch(function(error){console.error(error);$("reports-body").innerHTML='<tr><td colspan="10"><div class="hw-empty">The report archive could not load its published artifacts.</div></td></tr>';$("reports-mobile").innerHTML='<div class="hw-empty">The report archive could not load its published artifacts.</div>';});}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot);else boot();
}());
